// Telegram Bot SDK for Swift (unofficial).
// This file is autogenerated by API/generate_wrappers.rb script.

import Foundation
import Dispatch

public extension TelegramBot {
    typealias AnswerCallbackQueryCompletion = (_ result: Bool?, _ error: DataTaskError?) -> ()

    /// Use this method to send answers to callback queries sent from inline keyboards. The answer will be displayed to the user as a notification at the top of the chat screen or as an alert. On success, True is returned.
    /// - Parameters:
    ///     - callback_query_id: Unique identifier for the query to be answered
    ///     - text: Text of the notification. If not specified, nothing will be shown to the user, 0-200 characters
    ///     - show_alert: If true, an alert will be shown by the client instead of a notification at the top of the chat screen. Defaults to false.
    /// - Returns: Bool on success. Nil on error, in which case `TelegramBot.lastError` contains the details.
    /// - Note: Blocking version of the method.
    ///
    /// - SeeAlso: <https://core.telegram.org/bots/api#answercallbackquery>
    @discardableResult
    public func answerCallbackQuerySync(
            callback_query_id: String,
            text: String? = nil,
            show_alert: Bool? = nil,
            _ parameters: [String: Any?] = [:]) -> Bool? {
        return requestSync("answerCallbackQuery", defaultParameters["answerCallbackQuery"], parameters, [
            "callback_query_id": callback_query_id,
            "text": text,
            "show_alert": show_alert])
    }

    /// Use this method to send answers to callback queries sent from inline keyboards. The answer will be displayed to the user as a notification at the top of the chat screen or as an alert. On success, True is returned.
    /// - Parameters:
    ///     - callback_query_id: Unique identifier for the query to be answered
    ///     - text: Text of the notification. If not specified, nothing will be shown to the user, 0-200 characters
    ///     - show_alert: If true, an alert will be shown by the client instead of a notification at the top of the chat screen. Defaults to false.
    /// - Returns: Bool on success. Nil on error, in which case `error` contains the details.
    /// - Note: Asynchronous version of the method.
    ///
    /// - SeeAlso: <https://core.telegram.org/bots/api#answercallbackquery>
    public func answerCallbackQueryAsync(
            callback_query_id: String,
            text: String? = nil,
            show_alert: Bool? = nil,
            _ parameters: [String: Any?] = [:],
            queue: DispatchQueue = .main,
            completion: AnswerCallbackQueryCompletion? = nil) {
        return requestAsync("answerCallbackQuery", defaultParameters["answerCallbackQuery"], parameters, [
            "callback_query_id": callback_query_id,
            "text": text,
            "show_alert": show_alert],
            queue: queue, completion: completion)
    }
}

