// Telegram Bot SDK for Swift (unofficial).
// This file is autogenerated by API/generate_wrappers.rb script.

import Foundation
import Dispatch

public extension TelegramBot {
    typealias EditMessageCaptionCompletion = (_ result: Message?, _ error: DataTaskError?) -> ()

    /// Use this method to edit captions of messages sent by the bot or via the bot (for inline bots). On success, if edited message is sent by the bot, the edited Message is returned, otherwise True is returned.
    /// - Parameters:
    ///     - chat_id: Required if inline_message_id is not specified. Unique identifier for the target chat or username of the target channel (in the format @channelusername)
    ///     - message_id: Required if inline_message_id is not specified. Unique identifier of the sent message
    ///     - inline_message_id: Required if chat_id and message_id are not specified. Identifier of the inline message
    ///     - caption: New caption of the message
    ///     - reply_markup: A JSON-serialized object for an inline keyboard.
    /// - Returns: Message on success. Nil on error, in which case `TelegramBot.lastError` contains the details.
    /// - Note: Blocking version of the method.
    ///
    /// - SeeAlso: <https://core.telegram.org/bots/api#editmessagecaption>
    @discardableResult
    public func editMessageCaptionSync(
            chat_id: ChatId? = nil,
            message_id: Int? = nil,
            inline_message_id: String? = nil,
            caption: String? = nil,
            reply_markup: InlineKeyboardMarkup? = nil,
            _ parameters: [String: Any?] = [:]) -> Message? {
        return requestSync("editMessageCaption", defaultParameters["editMessageCaption"], parameters, [
            "chat_id": chat_id,
            "message_id": message_id,
            "inline_message_id": inline_message_id,
            "caption": caption,
            "reply_markup": reply_markup])
    }

    /// Use this method to edit captions of messages sent by the bot or via the bot (for inline bots). On success, if edited message is sent by the bot, the edited Message is returned, otherwise True is returned.
    /// - Parameters:
    ///     - chat_id: Required if inline_message_id is not specified. Unique identifier for the target chat or username of the target channel (in the format @channelusername)
    ///     - message_id: Required if inline_message_id is not specified. Unique identifier of the sent message
    ///     - inline_message_id: Required if chat_id and message_id are not specified. Identifier of the inline message
    ///     - caption: New caption of the message
    ///     - reply_markup: A JSON-serialized object for an inline keyboard.
    /// - Returns: Message on success. Nil on error, in which case `error` contains the details.
    /// - Note: Asynchronous version of the method.
    ///
    /// - SeeAlso: <https://core.telegram.org/bots/api#editmessagecaption>
    public func editMessageCaptionAsync(
            chat_id: ChatId? = nil,
            message_id: Int? = nil,
            inline_message_id: String? = nil,
            caption: String? = nil,
            reply_markup: InlineKeyboardMarkup? = nil,
            _ parameters: [String: Any?] = [:],
            queue: DispatchQueue = .main,
            completion: EditMessageCaptionCompletion? = nil) {
        return requestAsync("editMessageCaption", defaultParameters["editMessageCaption"], parameters, [
            "chat_id": chat_id,
            "message_id": message_id,
            "inline_message_id": inline_message_id,
            "caption": caption,
            "reply_markup": reply_markup],
            queue: queue, completion: completion)
    }
}

