// Telegram Bot SDK for Swift (unofficial).
// This file is autogenerated by API/generate_wrappers.rb script.

import Foundation


/// This object represents the content of a media message to be sent. It should be one of
/// InputMediaPhoto
/// InputMediaVideo
///
/// - SeeAlso: <https://core.telegram.org/bots/api#inputmedia>

public protocol InputMedia: JsonConvertible {
    /// Original JSON for fields not yet added to Swift structures.
    //var internalJson: JSON { get set }
}

extension InputMediaPhoto: InputMedia {
}

extension InputMediaVideo: InputMedia {
}
