// Telegram Bot SDK for Swift (unofficial).
// This file is autogenerated by API/generate_wrappers.rb script.

import Foundation
import Dispatch

public extension TelegramBot {
    typealias SetGameScoreCompletion = (_ result: Bool?, _ error: DataTaskError?) -> ()

    /// Use this method to set the score of the specified user in a game. On success, if the message was sent by the bot, returns the edited Message, otherwise returns True. Returns an error, if the new score is not greater than the user's current score in the chat and force is False.
    /// - Parameters:
    ///     - user_id: User identifier
    ///     - score: New score, must be non-negative
    ///     - force: Pass True, if the high score is allowed to decrease. This can be useful when fixing mistakes or banning cheaters
    ///     - disable_edit_message: Pass True, if the game message should not be automatically edited to include the current scoreboard
    ///     - chat_id: Required if inline_message_id is not specified. Unique identifier for the target chat (or username of the target channel in the format @channelusername)
    ///     - message_id: Required if inline_message_id is not specified. Identifier of the sent message
    ///     - inline_message_id: Required if chat_id and message_id are not specified. Identifier of the inline message
    /// - Returns: Bool on success. Nil on error, in which case `TelegramBot.lastError` contains the details.
    /// - Note: Blocking version of the method.
    ///
    /// - SeeAlso: <https://core.telegram.org/bots/api#setgamescore>
    @discardableResult
    public func setGameScoreSync(
            user_id: Int64,
            score: Int,
            force: Bool? = nil,
            disable_edit_message: Bool? = nil,
            chat_id: ChatId? = nil,
            message_id: Int? = nil,
            inline_message_id: String? = nil,
            _ parameters: [String: Any?] = [:]) -> Bool? {
        return requestSync("setGameScore", defaultParameters["setGameScore"], parameters, [
            "user_id": user_id,
            "score": score,
            "force": force,
            "disable_edit_message": disable_edit_message,
            "chat_id": chat_id,
            "message_id": message_id,
            "inline_message_id": inline_message_id])
    }

    /// Use this method to set the score of the specified user in a game. On success, if the message was sent by the bot, returns the edited Message, otherwise returns True. Returns an error, if the new score is not greater than the user's current score in the chat and force is False.
    /// - Parameters:
    ///     - user_id: User identifier
    ///     - score: New score, must be non-negative
    ///     - force: Pass True, if the high score is allowed to decrease. This can be useful when fixing mistakes or banning cheaters
    ///     - disable_edit_message: Pass True, if the game message should not be automatically edited to include the current scoreboard
    ///     - chat_id: Required if inline_message_id is not specified. Unique identifier for the target chat (or username of the target channel in the format @channelusername)
    ///     - message_id: Required if inline_message_id is not specified. Identifier of the sent message
    ///     - inline_message_id: Required if chat_id and message_id are not specified. Identifier of the inline message
    /// - Returns: Bool on success. Nil on error, in which case `error` contains the details.
    /// - Note: Asynchronous version of the method.
    ///
    /// - SeeAlso: <https://core.telegram.org/bots/api#setgamescore>
    public func setGameScoreAsync(
            user_id: Int64,
            score: Int,
            force: Bool? = nil,
            disable_edit_message: Bool? = nil,
            chat_id: ChatId? = nil,
            message_id: Int? = nil,
            inline_message_id: String? = nil,
            _ parameters: [String: Any?] = [:],
            queue: DispatchQueue = .main,
            completion: SetGameScoreCompletion? = nil) {
        return requestAsync("setGameScore", defaultParameters["setGameScore"], parameters, [
            "user_id": user_id,
            "score": score,
            "force": force,
            "disable_edit_message": disable_edit_message,
            "chat_id": chat_id,
            "message_id": message_id,
            "inline_message_id": inline_message_id],
            queue: queue, completion: completion)
    }
}

