// Telegram Bot SDK for Swift (unofficial).
// This file is autogenerated by API/generate_wrappers.rb script.

import Foundation
import Dispatch

public extension TelegramBot {
    typealias PromoteChatMemberCompletion = (_ result: Bool?, _ error: DataTaskError?) -> ()

    /// Use this method to promote or demote a user in a supergroup or a channel. The bot must be an administrator in the chat for this to work and must have the appropriate admin rights. Pass False for all boolean parameters to demote a user. Returns True on success.
    /// - Parameters:
    ///     - chat_id: Unique identifier for the target chat or username of the target channel (in the format @channelusername)
    ///     - user_id: Unique identifier of the target user
    ///     - can_change_info: Pass True, if the administrator can change chat title, photo and other settings
    ///     - can_post_messages: Pass True, if the administrator can create channel posts, channels only
    ///     - can_edit_messages: Pass True, if the administrator can edit messages of other users and can pin messages, channels only
    ///     - can_delete_messages: Pass True, if the administrator can delete messages of other users
    ///     - can_invite_users: Pass True, if the administrator can invite new users to the chat
    ///     - can_restrict_members: Pass True, if the administrator can restrict, ban or unban chat members
    ///     - can_pin_messages: Pass True, if the administrator can pin messages, supergroups only
    ///     - can_promote_members: Pass True, if the administrator can add new administrators with a subset of his own privileges or demote administrators that he has promoted, directly or indirectly (promoted by administrators that were appointed by him)
    /// - Returns: Bool on success. Nil on error, in which case `TelegramBot.lastError` contains the details.
    /// - Note: Blocking version of the method.
    ///
    /// - SeeAlso: <https://core.telegram.org/bots/api#promotechatmember>
    @discardableResult
    public func promoteChatMemberSync(
            chat_id: ChatId,
            user_id: Int64,
            can_change_info: Bool? = nil,
            can_post_messages: Bool? = nil,
            can_edit_messages: Bool? = nil,
            can_delete_messages: Bool? = nil,
            can_invite_users: Bool? = nil,
            can_restrict_members: Bool? = nil,
            can_pin_messages: Bool? = nil,
            can_promote_members: Bool? = nil,
            _ parameters: [String: Any?] = [:]) -> Bool? {
        return requestSync("promoteChatMember", defaultParameters["promoteChatMember"], parameters, [
            "chat_id": chat_id,
            "user_id": user_id,
            "can_change_info": can_change_info,
            "can_post_messages": can_post_messages,
            "can_edit_messages": can_edit_messages,
            "can_delete_messages": can_delete_messages,
            "can_invite_users": can_invite_users,
            "can_restrict_members": can_restrict_members,
            "can_pin_messages": can_pin_messages,
            "can_promote_members": can_promote_members])
    }

    /// Use this method to promote or demote a user in a supergroup or a channel. The bot must be an administrator in the chat for this to work and must have the appropriate admin rights. Pass False for all boolean parameters to demote a user. Returns True on success.
    /// - Parameters:
    ///     - chat_id: Unique identifier for the target chat or username of the target channel (in the format @channelusername)
    ///     - user_id: Unique identifier of the target user
    ///     - can_change_info: Pass True, if the administrator can change chat title, photo and other settings
    ///     - can_post_messages: Pass True, if the administrator can create channel posts, channels only
    ///     - can_edit_messages: Pass True, if the administrator can edit messages of other users and can pin messages, channels only
    ///     - can_delete_messages: Pass True, if the administrator can delete messages of other users
    ///     - can_invite_users: Pass True, if the administrator can invite new users to the chat
    ///     - can_restrict_members: Pass True, if the administrator can restrict, ban or unban chat members
    ///     - can_pin_messages: Pass True, if the administrator can pin messages, supergroups only
    ///     - can_promote_members: Pass True, if the administrator can add new administrators with a subset of his own privileges or demote administrators that he has promoted, directly or indirectly (promoted by administrators that were appointed by him)
    /// - Returns: Bool on success. Nil on error, in which case `error` contains the details.
    /// - Note: Asynchronous version of the method.
    ///
    /// - SeeAlso: <https://core.telegram.org/bots/api#promotechatmember>
    public func promoteChatMemberAsync(
            chat_id: ChatId,
            user_id: Int64,
            can_change_info: Bool? = nil,
            can_post_messages: Bool? = nil,
            can_edit_messages: Bool? = nil,
            can_delete_messages: Bool? = nil,
            can_invite_users: Bool? = nil,
            can_restrict_members: Bool? = nil,
            can_pin_messages: Bool? = nil,
            can_promote_members: Bool? = nil,
            _ parameters: [String: Any?] = [:],
            queue: DispatchQueue = .main,
            completion: PromoteChatMemberCompletion? = nil) {
        return requestAsync("promoteChatMember", defaultParameters["promoteChatMember"], parameters, [
            "chat_id": chat_id,
            "user_id": user_id,
            "can_change_info": can_change_info,
            "can_post_messages": can_post_messages,
            "can_edit_messages": can_edit_messages,
            "can_delete_messages": can_delete_messages,
            "can_invite_users": can_invite_users,
            "can_restrict_members": can_restrict_members,
            "can_pin_messages": can_pin_messages,
            "can_promote_members": can_promote_members],
            queue: queue, completion: completion)
    }
}

