// Telegram Bot SDK for Swift (unofficial).
// This file is autogenerated by API/generate_wrappers.rb script.

import Foundation
import SwiftyJSON

/// You can provide an animation for your game so that it looks stylish in chats (check out Lumberjack for an example). This object represents an animation file to be displayed in the message containing a game.
///
/// - SeeAlso: <https://core.telegram.org/bots/api#animation>

public struct Animation: JsonConvertible {
    /// Original JSON for fields not yet added to Swift structures.
    public var json: JSON

    /// Unique file identifier
    public var file_id: String {
        get { return json["file_id"].stringValue }
        set { json["file_id"].stringValue = newValue }
    }

    /// Optional. Animation thumbnail as defined by sender
    public var thumb: PhotoSize? {
        get {
            let value = json["thumb"]
            return value.isNullOrUnknown ? nil : PhotoSize(json: value)
        }
        set {
            json["thumb"] = newValue?.json ?? JSON.null
        }
    }

    /// Optional. Original animation filename as defined by sender
    public var file_name: String? {
        get { return json["file_name"].string }
        set { json["file_name"].string = newValue }
    }

    /// Optional. MIME type of the file as defined by sender
    public var mime_type: String? {
        get { return json["mime_type"].string }
        set { json["mime_type"].string = newValue }
    }

    /// Optional. File size
    public var file_size: Int? {
        get { return json["file_size"].int }
        set { json["file_size"].int = newValue }
    }

    public init(json: JSON = [:]) {
        self.json = json
    }
}
