// Telegram Bot SDK for Swift (unofficial).
// This file is autogenerated by API/generate_wrappers.rb script.

import Foundation
import SwiftyJSON

/// This object represents a chat photo.
///
/// - SeeAlso: <https://core.telegram.org/bots/api#chatphoto>

public struct ChatPhoto: JsonConvertible {
    /// Original JSON for fields not yet added to Swift structures.
    public var json: JSON

    /// Unique file identifier of small (160x160) chat photo. This file_id can be used only for photo download.
    public var small_file_id: String {
        get { return json["small_file_id"].stringValue }
        set { json["small_file_id"].stringValue = newValue }
    }

    /// Unique file identifier of big (640x640) chat photo. This file_id can be used only for photo download.
    public var big_file_id: String {
        get { return json["big_file_id"].stringValue }
        set { json["big_file_id"].stringValue = newValue }
    }

    public init(json: JSON = [:]) {
        self.json = json
    }
}
