// Telegram Bot SDK for Swift (unofficial).
// This file is autogenerated by API/generate_wrappers.rb script.

import Foundation


/// This object represents a chat photo.
///
/// - SeeAlso: <https://core.telegram.org/bots/api#chatphoto>

public struct ChatPhoto: JsonConvertible, InternalJsonConvertible {
    /// Original JSON for fields not yet added to Swift structures.
    public var json: Any {
        get {
            return internalJson.object
        }
        set {
            internalJson = JSON(newValue)
        }
    }
    internal var internalJson: JSON

    /// Unique file identifier of small (160x160) chat photo. This file_id can be used only for photo download.
    public var smallFileId: String {
        get { return internalJson["small_file_id"].stringValue }
        set { internalJson["small_file_id"].stringValue = newValue }
    }

    /// Unique file identifier of big (640x640) chat photo. This file_id can be used only for photo download.
    public var bigFileId: String {
        get { return internalJson["big_file_id"].stringValue }
        set { internalJson["big_file_id"].stringValue = newValue }
    }

    internal init(internalJson: JSON = [:]) {
        self.internalJson = internalJson
    }
    public init(json: Any) {
        self.internalJson = JSON(json)
    }
    public init(data: Data) {
        self.internalJson = JSON(data: data)
    }
}
