// Telegram Bot SDK for Swift (unofficial).
// This file is autogenerated by API/generate_wrappers.rb script.

import Foundation


/// This object represents a phone contact.
///
/// - SeeAlso: <https://core.telegram.org/bots/api#contact>

public struct Contact: JsonConvertible, InternalJsonConvertible {
    /// Original JSON for fields not yet added to Swift structures.
    public var json: Any {
        get {
            return internalJson.object
        }
        set {
            internalJson = JSON(newValue)
        }
    }
    internal var internalJson: JSON

    /// Contact's phone number
    public var phoneNumber: String {
        get { return internalJson["phone_number"].stringValue }
        set { internalJson["phone_number"].stringValue = newValue }
    }

    /// Contact's first name
    public var firstName: String {
        get { return internalJson["first_name"].stringValue }
        set { internalJson["first_name"].stringValue = newValue }
    }

    /// Optional. Contact's last name
    public var lastName: String? {
        get { return internalJson["last_name"].string }
        set { internalJson["last_name"].string = newValue }
    }

    /// Optional. Contact's user identifier in Telegram
    public var userId: Int64? {
        get { return internalJson["user_id"].int64 }
        set { internalJson["user_id"].int64 = newValue }
    }

    internal init(internalJson: JSON = [:]) {
        self.internalJson = internalJson
    }
    public init(json: Any) {
        self.internalJson = JSON(json)
    }
    public init(data: Data) {
        self.internalJson = JSON(data: data)
    }
}
