// Telegram Bot SDK for Swift (unofficial).
// This file is autogenerated by API/generate_wrappers.rb script.

import Foundation
import SwiftyJSON

/// This object represents an incoming inline query. When the user sends an empty query, your bot could return some default or trending results.
///
/// - SeeAlso: <https://core.telegram.org/bots/api#inlinequery>

public struct InlineQuery: JsonConvertible {
    /// Original JSON for fields not yet added to Swift structures.
    public var json: JSON

    /// Unique identifier for this query
    public var id: String {
        get { return json["id"].stringValue }
        set { json["id"].stringValue = newValue }
    }

    /// Sender
    public var from: User {
        get { return User(json: json["from"]) }
        set { json["from"] = newValue.json }
    }

    /// Optional. Sender location, only for bots that request user location
    public var location: Location? {
        get {
            let value = json["location"]
            return value.isNullOrUnknown ? nil : Location(json: value)
        }
        set {
            json["location"] = newValue?.json ?? JSON.null
        }
    }

    /// Text of the query (up to 512 characters)
    public var query: String {
        get { return json["query"].stringValue }
        set { json["query"].stringValue = newValue }
    }

    /// Offset of the results to be returned, can be controlled by the bot
    public var offset: String {
        get { return json["offset"].stringValue }
        set { json["offset"].stringValue = newValue }
    }

    public init(json: JSON = [:]) {
        self.json = json
    }
}
