// Telegram Bot SDK for Swift (unofficial).
// This file is autogenerated by API/generate_wrappers.rb script.

import Foundation
import SwiftyJSON

/// Represents the content of a location message to be sent as the result of an inline query.
///
/// - SeeAlso: <https://core.telegram.org/bots/api#inputlocationmessagecontent>

public struct InputLocationMessageContent: JsonConvertible {
    /// Original JSON for fields not yet added to Swift structures.
    public var json: JSON

    /// Latitude of the location in degrees
    public var latitude: Float {
        get { return json["latitude"].floatValue }
        set { json["latitude"].floatValue = newValue }
    }

    /// Longitude of the location in degrees
    public var longitude: Float {
        get { return json["longitude"].floatValue }
        set { json["longitude"].floatValue = newValue }
    }

    public init(json: JSON = [:]) {
        self.json = json
    }
}
