// Telegram Bot SDK for Swift (unofficial).
// This file is autogenerated by API/generate_wrappers.rb script.

import Foundation
import SwiftyJSON

/// This object contains basic information about an invoice.
///
/// - SeeAlso: <https://core.telegram.org/bots/api#invoice>

public struct Invoice: JsonConvertible {
    /// Original JSON for fields not yet added to Swift structures.
    public var json: JSON

    /// Product name
    public var title: String {
        get { return json["title"].stringValue }
        set { json["title"].stringValue = newValue }
    }

    /// Product description
    public var description: String {
        get { return json["description"].stringValue }
        set { json["description"].stringValue = newValue }
    }

    /// Unique bot deep-linking parameter that can be used to generate this invoice
    public var start_parameter: String {
        get { return json["start_parameter"].stringValue }
        set { json["start_parameter"].stringValue = newValue }
    }

    /// Three-letter ISO 4217 currency code
    public var currency: String {
        get { return json["currency"].stringValue }
        set { json["currency"].stringValue = newValue }
    }

    /// Total price in the smallest units of the currency (integer, not float/double). For example, for a price of US$ 1.45 pass amount = 145. See the exp parameter in currencies.json, it shows the number of digits past the decimal point for each currency (2 for the majority of currencies).
    public var total_amount: Int {
        get { return json["total_amount"].intValue }
        set { json["total_amount"].intValue = newValue }
    }

    public init(json: JSON = [:]) {
        self.json = json
    }
}
