// Telegram Bot SDK for Swift (unofficial).
// This file is autogenerated by API/generate_wrappers.rb script.

import Foundation
import SwiftyJSON

/// This object represents a portion of the price for goods or services.
///
/// - SeeAlso: <https://core.telegram.org/bots/api#labeledprice>

public struct LabeledPrice: JsonConvertible {
    /// Original JSON for fields not yet added to Swift structures.
    public var json: JSON

    /// Portion label
    public var label: String {
        get { return json["label"].stringValue }
        set { json["label"].stringValue = newValue }
    }

    /// Price of the product in the smallest units of the currency (integer, not float/double). For example, for a price of US$ 1.45 pass amount = 145. See the exp parameter in currencies.json, it shows the number of digits past the decimal point for each currency (2 for the majority of currencies).
    public var amount: Int {
        get { return json["amount"].intValue }
        set { json["amount"].intValue = newValue }
    }

    public init(json: JSON = [:]) {
        self.json = json
    }
}
