// Telegram Bot SDK for Swift (unofficial).
// This file is autogenerated by API/generate_wrappers.rb script.

import Foundation
import SwiftyJSON

/// This object describes the position on faces where a mask should be placed by default.
///
/// - SeeAlso: <https://core.telegram.org/bots/api#maskposition>

public struct MaskPosition: JsonConvertible {
    /// Original JSON for fields not yet added to Swift structures.
    public var json: JSON

    /// The part of the face relative to which the mask should be placed. One of “forehead”, “eyes”, “mouth”, or “chin”.
    public var point: String {
        get { return json["point"].stringValue }
        set { json["point"].stringValue = newValue }
    }

    /// Shift by X-axis measured in widths of the mask scaled to the face size, from left to right. For example, choosing -1.0 will place mask just to the left of the default mask position.
    public var x_shift: Float {
        get { return json["x_shift"].floatValue }
        set { json["x_shift"].floatValue = newValue }
    }

    /// Shift by Y-axis measured in heights of the mask scaled to the face size, from top to bottom. For example, 1.0 will place the mask just below the default mask position.
    public var y_shift: Float {
        get { return json["y_shift"].floatValue }
        set { json["y_shift"].floatValue = newValue }
    }

    /// Mask scaling coefficient. For example, 2.0 means double size.
    public var scale: Float {
        get { return json["scale"].floatValue }
        set { json["scale"].floatValue = newValue }
    }

    public init(json: JSON = [:]) {
        self.json = json
    }
}
