// Telegram Bot SDK for Swift (unofficial).
// This file is autogenerated by API/generate_wrappers.rb script.

import Foundation
import SwiftyJSON

/// This object represents one size of a photo or a file / sticker thumbnail.
///
/// - SeeAlso: <https://core.telegram.org/bots/api#photosize>

public struct PhotoSize: JsonConvertible {
    /// Original JSON for fields not yet added to Swift structures.
    public var json: JSON

    /// Unique identifier for this file
    public var file_id: String {
        get { return json["file_id"].stringValue }
        set { json["file_id"].stringValue = newValue }
    }

    /// Photo width
    public var width: Int {
        get { return json["width"].intValue }
        set { json["width"].intValue = newValue }
    }

    /// Photo height
    public var height: Int {
        get { return json["height"].intValue }
        set { json["height"].intValue = newValue }
    }

    /// Optional. File size
    public var file_size: Int? {
        get { return json["file_size"].int }
        set { json["file_size"].int = newValue }
    }

    public init(json: JSON = [:]) {
        self.json = json
    }
}
