// Telegram Bot SDK for Swift (unofficial).
// This file is autogenerated by API/generate_wrappers.rb script.

import Foundation
import SwiftyJSON

/// This object represents one shipping option.
///
/// - SeeAlso: <https://core.telegram.org/bots/api#shippingoption>

public struct ShippingOption: JsonConvertible {
    /// Original JSON for fields not yet added to Swift structures.
    public var json: JSON

    /// Shipping option identifier
    public var id: String {
        get { return json["id"].stringValue }
        set { json["id"].stringValue = newValue }
    }

    /// Option title
    public var title: String {
        get { return json["title"].stringValue }
        set { json["title"].stringValue = newValue }
    }

    /// List of price portions
    public var prices: [LabeledPrice] {
        get { return json["prices"].arrayValue() }
        set { json["prices"] = JSON.initFrom(newValue) }
    }

    public init(json: JSON = [:]) {
        self.json = json
    }
}
