// Telegram Bot SDK for Swift (unofficial).
// This file is autogenerated by API/generate_wrappers.rb script.

import Foundation
import SwiftyJSON

/// This object represents a video message (available in Telegram apps as of v.4.0).
///
/// - SeeAlso: <https://core.telegram.org/bots/api#videonote>

public struct VideoNote: JsonConvertible {
    /// Original JSON for fields not yet added to Swift structures.
    public var json: JSON

    /// Unique identifier for this file
    public var file_id: String {
        get { return json["file_id"].stringValue }
        set { json["file_id"].stringValue = newValue }
    }

    /// Video width and height as defined by sender
    public var length: Int {
        get { return json["length"].intValue }
        set { json["length"].intValue = newValue }
    }

    /// Duration of the video in seconds as defined by sender
    public var duration: Int {
        get { return json["duration"].intValue }
        set { json["duration"].intValue = newValue }
    }

    /// Optional. Video thumbnail
    public var thumb: PhotoSize? {
        get {
            let value = json["thumb"]
            return value.isNullOrUnknown ? nil : PhotoSize(json: value)
        }
        set {
            json["thumb"] = newValue?.json ?? JSON.null
        }
    }

    /// Optional. File size
    public var file_size: Int? {
        get { return json["file_size"].int }
        set { json["file_size"].int = newValue }
    }

    public init(json: JSON = [:]) {
        self.json = json
    }
}
