// Telegram Bot SDK for Swift (unofficial).
// This file is autogenerated by API/generate_wrappers.rb script.

import Foundation
import SwiftyJSON

/// This object contains information about one member of the chat.
///
/// - SeeAlso: <https://core.telegram.org/bots/api#chatmember>

public struct ChatMember: JsonConvertible {
    /// Original JSON for fields not yet added to Swift structures.
    public var json: JSON

    /// Information about the user
    public var user: User {
        get { return User(json: json["user"]) }
        set { json["user"] = newValue.json }
    }

    /// The member's status in the chat. Can be “creator”, “administrator”, “member”, “left” or “kicked”
    public var status_string: String {
        get { return json["status"].stringValue }
        set { json["status"].stringValue = newValue }
    }

    public init(json: JSON = [:]) {
        self.json = json
    }
}
