// Telegram Bot SDK for Swift (unofficial).
// This file is autogenerated by API/generate_wrappers.rb script.

import Foundation
import SwiftyJSON

/// This object represents a phone contact.
///
/// - SeeAlso: <https://core.telegram.org/bots/api#contact>

public struct Contact: JsonConvertible {
    /// Original JSON for fields not yet added to Swift structures.
    public var json: JSON

    /// Contact's phone number
    public var phone_number: String {
        get { return json["phone_number"].stringValue }
        set { json["phone_number"].stringValue = newValue }
    }

    /// Contact's first name
    public var first_name: String {
        get { return json["first_name"].stringValue }
        set { json["first_name"].stringValue = newValue }
    }

    /// Optional. Contact's last name
    public var last_name: String? {
        get { return json["last_name"].string }
        set { json["last_name"].string = newValue }
    }

    /// Optional. Contact's user identifier in Telegram
    public var user_id: Int64? {
        get { return json["user_id"].int64 }
        set { json["user_id"].int64 = newValue }
    }

    public init(json: JSON = [:]) {
        self.json = json
    }
}
