// Telegram Bot SDK for Swift (unofficial).
// This file is autogenerated by API/generate_wrappers.rb script.

import Foundation
import SwiftyJSON

/// Represents the content of a contact message to be sent as the result of an inline query.
///
/// - SeeAlso: <https://core.telegram.org/bots/api#inputcontactmessagecontent>

public struct InputContactMessageContent: JsonConvertible {
    /// Original JSON for fields not yet added to Swift structures.
    public var json: JSON

    /// Contact's phone number
    public var phone_number: String {
        get { return json["phone_number"].stringValue }
        set { json["phone_number"].stringValue = newValue }
    }

    /// Contact's first name
    public var first_name: String {
        get { return json["first_name"].stringValue }
        set { json["first_name"].stringValue = newValue }
    }

    /// Optional. Contact's last name
    public var last_name: String? {
        get { return json["last_name"].string }
        set { json["last_name"].string = newValue }
    }

    public init(json: JSON = [:]) {
        self.json = json
    }
}
