// Telegram Bot SDK for Swift (unofficial).
// This file is autogenerated by API/generate_wrappers.rb script.

import Foundation
import SwiftyJSON

/// This object represents the content of a message to be sent as a result of an inline query. Telegram clients currently support the following 4 types:
/// InputTextMessageContent
/// InputLocationMessageContent
/// InputVenueMessageContent
/// InputContactMessageContent
///
/// - SeeAlso: <https://core.telegram.org/bots/api#inputmessagecontent>

public struct InputMessageContent: JsonConvertible {
    /// Original JSON for fields not yet added to Swift structures.
    public var json: JSON

    public init(json: JSON = [:]) {
        self.json = json
    }
}
