// Telegram Bot SDK for Swift (unofficial).
// This file is autogenerated by API/generate_wrappers.rb script.

import Foundation
import SwiftyJSON

/// This object represents one special entity in a text message. For example, hashtags, usernames, URLs, etc.
///
/// - SeeAlso: <https://core.telegram.org/bots/api#messageentity>

public struct MessageEntity: JsonConvertible {
    /// Original JSON for fields not yet added to Swift structures.
    public var json: JSON

    /// Type of the entity. Can be mention (@username), hashtag, bot_command, url, email, bold (bold text), italic (italic text), code (monowidth string), pre (monowidth block), text_link (for clickable text URLs), text_mention (for users without usernames)
    public var type_string: String {
        get { return json["type"].stringValue }
        set { json["type"].stringValue = newValue }
    }

    /// Offset in UTF-16 code units to the start of the entity
    public var offset: Int {
        get { return json["offset"].intValue }
        set { json["offset"].intValue = newValue }
    }

    /// Length of the entity in UTF-16 code units
    public var length: Int {
        get { return json["length"].intValue }
        set { json["length"].intValue = newValue }
    }

    /// Optional. For “text_link” only, url that will be opened after user taps on the text
    public var url: String? {
        get { return json["url"].string }
        set { json["url"].string = newValue }
    }

    /// Optional. For “text_mention” only, the mentioned user
    public var user: User? {
        get {
            let value = json["user"]
            return value.isNullOrUnknown ? nil : User(json: value)
        }
        set {
            json["user"] = newValue?.json ?? JSON.null
        }
    }

    public init(json: JSON = [:]) {
        self.json = json
    }
}
