// Telegram Bot SDK for Swift (unofficial).
// This file is autogenerated by API/generate_wrappers.rb script.

import Foundation
import SwiftyJSON

/// This object represents a video file.
///
/// - SeeAlso: <https://core.telegram.org/bots/api#video>

public struct Video: JsonConvertible {
    /// Original JSON for fields not yet added to Swift structures.
    public var json: JSON

    /// Unique identifier for this file
    public var file_id: String {
        get { return json["file_id"].stringValue }
        set { json["file_id"].stringValue = newValue }
    }

    /// Video width as defined by sender
    public var width: Int {
        get { return json["width"].intValue }
        set { json["width"].intValue = newValue }
    }

    /// Video height as defined by sender
    public var height: Int {
        get { return json["height"].intValue }
        set { json["height"].intValue = newValue }
    }

    /// Duration of the video in seconds as defined by sender
    public var duration: Int {
        get { return json["duration"].intValue }
        set { json["duration"].intValue = newValue }
    }

    /// Optional. Video thumbnail
    public var thumb: PhotoSize? {
        get {
            let value = json["thumb"]
            return value.isNullOrUnknown ? nil : PhotoSize(json: value)
        }
        set {
            json["thumb"] = newValue?.json ?? JSON.null
        }
    }

    /// Optional. Mime type of a file as defined by sender
    public var mime_type: String? {
        get { return json["mime_type"].string }
        set { json["mime_type"].string = newValue }
    }

    /// Optional. File size
    public var file_size: Int? {
        get { return json["file_size"].int }
        set { json["file_size"].int = newValue }
    }

    public init(json: JSON = [:]) {
        self.json = json
    }
}
