// Telegram Bot SDK for Swift (unofficial).
// This file is autogenerated by API/generate_wrappers.rb script.

import Foundation
import SwiftyJSON

/// Contains information about the current status of a webhook.
///
/// - SeeAlso: <https://core.telegram.org/bots/api#webhookinfo>

public struct WebhookInfo: JsonConvertible {
    /// Original JSON for fields not yet added to Swift structures.
    public var json: JSON

    /// Webhook URL, may be empty if webhook is not set up
    public var url: String {
        get { return json["url"].stringValue }
        set { json["url"].stringValue = newValue }
    }

    /// True, if a custom certificate was provided for webhook certificate checks
    public var has_custom_certificate: Bool {
        get { return json["has_custom_certificate"].boolValue }
        set { json["has_custom_certificate"].boolValue = newValue }
    }

    /// Number of updates awaiting delivery
    public var pending_update_count: Int {
        get { return json["pending_update_count"].intValue }
        set { json["pending_update_count"].intValue = newValue }
    }

    /// Optional. Unix time for the most recent error that happened when trying to deliver an update via webhook
    public var last_error_date_unix: Int? {
        get { return json["last_error_date"].int }
        set { json["last_error_date"].int = newValue }
    }

    /// Optional. Error message in human-readable format for the most recent error that happened when trying to deliver an update via webhook
    public var last_error_message: String? {
        get { return json["last_error_message"].string }
        set { json["last_error_message"].string = newValue }
    }

    /// Optional. Maximum allowed number of simultaneous HTTPS connections to the webhook for update delivery
    public var max_connections: Int? {
        get { return json["max_connections"].int }
        set { json["max_connections"].int = newValue }
    }

    /// Optional. A list of update types the bot is subscribed to. Defaults to all update types
    public var allowed_updates: [String] {
        get { return json["allowed_updates"].arrayValue() }
        set { json["allowed_updates"] = newValue.isEmpty ? JSON.null : JSON.initFrom(newValue) }
    }

    public init(json: JSON = [:]) {
        self.json = json
    }
}
